$Game::Item::PopTime = 360000;

$startingAmount = 400;
$betaBonus = 100;

// Score grant tracking
if(isFile("config/Farming/scoreGrant.cs"))
	exec("config/Farming/scoreGrant.cs");

// Vehicle Costs
JeepVehicle.maxWheelSpeed = 22;
JeepSpring.force = 2000;
JeepSpring.damping = 5000;
HorseArmor.maxForwardSpeed = 12;
HorseArmor.maxForwardCrouchSpeed = 12;

hangglidervehicle.lift = 11;
hangglidervehicle.verticalSurfaceForce = 18;
hangglidervehicle.forwardThrust = 5;
hangglidervehicle.reverseThrust = 5;

$Farming::BappsMatCycleTime = 60 * 60 * 1000 | 0; // 1 hour
function addBappsMatStrings()
{
	addBappsMatString("gaming");
	addBappsMatString("bapps!");
	addBappsMatString("turnip");
	addBappsMatString("e.");
	addBappsMatString("tomato");
	addBappsMatString("at dos");
	addBappsMatString("onyo");
	addBappsMatString("lmao");
	addBappsMatString("wheeet");
	addBappsMatString("oh");
	addBappsMatString("sick");
	addBappsMatString("%0");
	addBappsMatString("%D");
	addBappsMatString("%7");
	addBappsMatString("8I");
	addBappsMatString(" ");
	addBappsMatString("83");
	addBappsMatString("?#!@*&");
	addBappsMatString("floor.");
	addBappsMatString("tork");
	addBappsMatString("<3");
	addBappsMatString("8==D");
	addBappsMatString("boklnd");
	addBappsMatString("beeb");
	addBappsMatString("brapps");
	addBappsMatString("borked");
	addBappsMatString("hewwo!");
	addBappsMatString("icup");
	addBappsMatString("o.");
	addBappsMatString("conan?");
	addBappsMatString("based.");
	addBappsMatString("FIGHT!");
	addBappsMatString("helpme");
	addBappsMatString("help");
	addBappsMatString("k.");
	addBappsMatString("no");
	addBappsMatString("ye");
	addBappsMatString("yeh.");
	addBappsMatString("feet");
	addBappsMatString("fruity");
	addBappsMatString("smelly");
	addBappsMatString("ctrl-k");
	addBappsMatString("alt f4");
	addBappsMatString("no way");
	addBappsMatString("ur mom");
	addBappsMatString("leave.");
	addBappsMatString("shup");
	addBappsMatString("knock!");
	addBappsMatString("hhhh");
	addBappsMatString("wowe");
	addBappsMatString("doge");
	addBappsMatString("chode.");
	addBappsMatString("speen!");
	addBappsMatString("push");
	addBappsMatString("ree!");
	addBappsMatString("die.");
	addBappsMatString("abcd");
	addBappsMatString("!sppab");
	addBappsMatString("spparb");
	addBappsMatString("matt");
	addBappsMatString("800815");
	addBappsMatString("lololo");
	addBappsMatString("lookup");
	addBappsMatString("vamos!");
	addBappsMatString("text");
	addBappsMatString("error.");
	addBappsMatString("todo");
	addBappsMatString("unused");
	addBappsMatString("temp");
	addBappsMatString("baps");
	addBappsMatString("christ");
	addBappsMatString("m'lady");
	addBappsMatString("cursed");
	addBappsMatString("bapp's");
	addBappsMatString("remove");
	addBappsMatString("delete");
	addBappsMatString("404.");
	addBappsMatString("bye.");
	addBappsMatString("run.");
	addBappsMatString("ooga");
	addBappsMatString("awooga");
	addBappsMatString("honk");
	addBappsMatString("b*pps.");
	addBappsMatString("mwah");
	addBappsMatString("waaagh");
	addBappsMatString("floor.");
	addBappsMatString("?2020?");
	addBappsMatString("!2025!");
	addBappsMatString("pemis.");
	addBappsMatString("%I");
	addBappsMatString("%>");
	addBappsMatString("yeet");
	addBappsMatString("weed");
	addBappsMatString("poopoo");
	addBappsMatString("peepee");
	addBappsMatString("lmao");
	addBappsMatString("toilet");
	addBappsMatString("mat.");
	addBappsMatString("uwu?");
	addBappsMatString("bruh");
	addBappsMatString("swag");
	addBappsMatString("what");
	addBappsMatString("u wot?");
	addBappsMatString("bri'sh");
	addBappsMatString("wifi");
	addBappsMatString("carrot");
	addBappsMatString("e!");
	addBappsMatString("    hi");
	addBappsMatString("potato");
	addBappsMatString("??????");
	addBappsMatString("shroom");
}
schedule(1000, 0, addBappsMatStrings);

$Farming::PostOfficeCycleTime = 1000 * 60 * 60 | 0;
function addPostOfficeStrings()
{
	addPostOfficeString(".post." TAB "office");
	addPostOfficeString(".send." TAB "office");
	addPostOfficeString("delete" TAB "office");
	addPostOfficeString("letter" TAB "place!");
	addPostOfficeString(".lick." TAB "here");
	addPostOfficeString(".poot." TAB "oofice");
	addPostOfficeString(".shit." TAB "orfice");
	addPostOfficeString(". do ." TAB "quests");
	addPostOfficeString(".sign." TAB "here");
	addPostOfficeString(".full." TAB "send");
	addPostOfficeString(".send." TAB "nudes?");
	addPostOfficeString(".mail." TAB "zone");
	addPostOfficeString(". no ." TAB "entry!");
	addPostOfficeString(".post." TAB "mortem");
	addPostOfficeString("please" TAB "donate");
	addPostOfficeString("broken" TAB "game");
	addPostOfficeString(".gone." TAB "postal");
	addPostOfficeString("conans" TAB "farmig");
	addPostOfficeString("ma    " TAB "il    ");
	addPostOfficeString(".fuck." TAB "stamps");
	addPostOfficeString("po off" TAB "st ice");
	addPostOfficeString("office" TAB ".post.");
	addPostOfficeString(".ofst." TAB "pofice");
	addPostOfficeString(".pomf." TAB "office");
	addPostOfficeString(".send." TAB "help");
	addPostOfficeString("");
	addPostOfficeString(".????." TAB "??????");
	addPostOfficeString(".post." TAB "??????");
	addPostOfficeString(".????." TAB "office");
	addPostOfficeString("uhhh i" TAB "forgor");
	addPostOfficeString(".duck." TAB "office");
	addPostOfficeString("mailed" TAB "it!!");
	addPostOfficeString(".post." TAB "modern");
	addPostOfficeString(".fake." TAB "stamps");
	addPostOfficeString(".real." TAB "stamps");
	addPostOfficeString(". no ." TAB "stamps");
	addPostOfficeString(". no ." TAB "mail");
	addPostOfficeString(".only." TAB "stamps");
	addPostOfficeString("behind" TAB "you!");
	addPostOfficeString(".slam." TAB "dumper");
	addPostOfficeString("always" TAB "late");
	addPostOfficeString(".mail." TAB "snails");
	addPostOfficeString(".post." TAB "haste!");
	addPostOfficeString("ufaywa" TAB "ynce");
	addPostOfficeString(".post." TAB "urself");
	addPostOfficeString(".uhh?." TAB "what");
	addPostOfficeString(".mail." TAB "fraud!");
	addPostOfficeString("do not" TAB "mail");
	addPostOfficeString("do not" TAB "send");
	addPostOfficeString("do not" TAB "post");
	addPostOfficeString("do not" TAB "delete");
	addPostOfficeString(".mail." TAB "hole");
	addPostOfficeString("418 im" TAB "teapot");
	addPostOfficeString("200 ok");
	addPostOfficeString("sealed" TAB "fate");
	addPostOfficeString(".post." TAB "onice?");
	addPostOfficeString(".slap." TAB "office");
	addPostOfficeString("fed-ex" TAB "escape");
	addPostOfficeString(".post." TAB "quest!");
	addPostOfficeString(".here." TAB "mail");
	addPostOfficeString(".mail." TAB "moding");
	addPostOfficeString("204 no" TAB "mail");
	addPostOfficeString(".cant." TAB "thinke");
	addPostOfficeString("brapps" TAB "post");
	addPostOfficeString(".enve." TAB "lope");
	addPostOfficeString(".gift." TAB "shop");
	addPostOfficeString("no! no" TAB "mail!!");
	addPostOfficeString("poasto" TAB "fune");
	addPostOfficeString("hidden" TAB "letter");
	addPostOfficeString("thanks" TAB "gpt!");
	addPostOfficeString("nothin" TAB "yet.");
	addPostOfficeString("access" TAB "denied");
	addPostOfficeString(".nope." TAB "nothin");
	addPostOfficeString(".ouch." TAB "office");
	addPostOfficeString("canyou" TAB "hearme");
	addPostOfficeString("let me" TAB "out!");
	addPostOfficeString(".mail." TAB "mancer");
	addPostOfficeString(".look." TAB "up");
	addPostOfficeString("ate my" TAB "stamps");
	addPostOfficeString("stamps" TAB "yummy!");
	addPostOfficeString(".butt." TAB "post");
	addPostOfficeString(". we ." TAB "cant");
	addPostOfficeString("conans" TAB "crash!");
	addPostOfficeString(".help." TAB "wanted");
	addPostOfficeString(".lmao." TAB "office");
	addPostOfficeString(". no ." TAB "escape");
	addPostOfficeString("your" TAB "mail");
	addPostOfficeString(".!@#$." TAB "office");
	addPostOfficeString(".post." TAB "!@#$*&");
	addPostOfficeString(".moil." TAB "affice");
	addPostOfficeString("stamps" TAB "office");
	addPostOfficeString("time" TAB "portal");
	addPostOfficeString(".post." TAB "card");
	addPostOfficeString("parcel" TAB "puns");
	addPostOfficeString("direct" TAB "mail");
	addPostOfficeString(".ship." TAB "me");
	addPostOfficeString("zipped" TAB "file");
	addPostOfficeString(".send." TAB "bobber");
	addPostOfficeString(". go ." TAB "phish!");
	addPostOfficeString(".sgep." TAB "office");
	addPostOfficeString("ownser" TAB "forog?");
	addPostOfficeString(".spam." TAB "office");
	addPostOfficeString("postal" TAB "nuts");
	addPostOfficeString(".mail." TAB "trash!");
	addPostOfficeString("e-mail" TAB "server");
	addPostOfficeString("floomp" TAB "office");
	addPostOfficeString(".post." TAB "marked");
	addPostOfficeString(".send." TAB "home");
	addPostOfficeString("packin" TAB "shmeat");
	addPostOfficeString(".wink." TAB "wink");
	addPostOfficeString("fruit" TAB "flies");
	addPostOfficeString(". ok ." TAB "bye!");
	addPostOfficeString("random" TAB "text");
	addPostOfficeString(".mail." TAB "chain!");
	addPostOfficeString("letter" TAB "bomb");
	addPostOfficeString(".shit." TAB "post");
	addPostOfficeString(".tele." TAB "gram");
	addPostOfficeString(".send." TAB "dudes!");
	addPostOfficeString("mailto" TAB "e@s.us");
	addPostOfficeString(".hate." TAB "mail");
	addPostOfficeString(".love." TAB "letter");
	addPostOfficeString("to me" TAB "from u");
	addPostOfficeString(".fish." TAB "office");
	addPostOfficeString(".com" TAB "post");
	addPostOfficeString(".open." TAB "letter");
	addPostOfficeString(".junk." TAB "mail");
	addPostOfficeString(".ship." TAB "things");
	addPostOfficeString(".ship." TAB "shape!");
	addPostOfficeString("repost" TAB "office");
	addPostOfficeString(".pice." TAB "offost");
	addPostOfficeString("no one" TAB "here");
	addPostOfficeString(".were." TAB "hiring");
	addPostOfficeString("finish" TAB "sign");
	addPostOfficeString("sign" TAB "done");
	addPostOfficeString("todo" TAB "sign");
	addPostOfficeString("todo" TAB "quests");
	addPostOfficeString("trunca" TAB "conten");
	addPostOfficeString("veggie" TAB "mail");
	addPostOfficeString(".many." TAB "errors");
	addPostOfficeString("parcel" TAB "office");
	addPostOfficeString(".bulk." TAB "mail");
	addPostOfficeString(".rear." TAB "access");
	addPostOfficeString("please" TAB "read");
	addPostOfficeString("" TAB "    hi");
	addPostOfficeString(".mail." TAB "room");
	addPostOfficeString(".mail." TAB "shack?");
	addPostOfficeString("wheres" TAB "mail");
	addPostOfficeString(".blok." TAB "mail");
	addPostOfficeString("..mmmm" TAB "mail");
	addPostOfficeString("cursed" TAB "post");
	addPostOfficeString(".plop." TAB "office");
	addPostOfficeString("potty" TAB "humor");
	addPostOfficeString("drive" TAB "thru!");
	addPostOfficeString(".free." TAB "hats");
	addPostOfficeString("squirt" TAB "office");
	addPostOfficeString(".dont." TAB "read");
	addPostOfficeString("e     ");
	addPostOfficeString("bottom" TAB "text");
	addPostOfficeString("its " TAB "2025??");
	addPostOfficeString("i love" TAB "you <3");
	addPostOfficeString("wat da" TAB "hell");
	addPostOfficeString(".xbox." TAB "live");
	addPostOfficeString(".good." TAB "night!");
	addPostOfficeString("i go" TAB "sleep.");
}
schedule(1000, 0, addPostOfficeStrings);